version: "3.9"
services:
  httpbin:
    restart: unless-stopped
    image: mccutchen/go-httpbin:v2.5.0
    ports:
      - 8080:8080
  coraza:
    restart: unless-stopped
    build:
      context: .
      target: coreruleset
  haproxy:
    restart: unless-stopped
    image: haproxy:2.9-alpine
    ports: [ "4000:80", "4443:443", "4001:4001" ]
    links:
      - "coraza:coraza"
      - "httpbin:httpbin"
    volumes:
      - type: bind
        source: ./docker/haproxy
        target: /usr/local/etc/haproxy
