version: "3.9"
services:
  httpbin:
    restart: unless-stopped
    image: mccutchen/go-httpbin:v2.9.0
    command: [ "/bin/go-httpbin", "-port", "8080" ]
    ports:
      - 8080:8080
  coraza:
    restart: unless-stopped
    build:
      context: .
      target: coreruleset
    volumes:
      - ./docker/e2e/e2e-rules.conf:/etc/coraza-spoa/rules/000-e2e-rules.conf
  haproxy:
    depends_on:
      - coraza
      - httpbin
    image: ${HAPROXY_IMAGE:-haproxy:2.7-alpine}
    command:
      [
        "sh",
        "-c",
        "haproxy -f /usr/local/etc/haproxy/haproxy.cfg | tee /var/lib/haproxy/hap.log"
      ]
    ports: [ "4000:80"]
    links:
      - "coraza:coraza"
      - "httpbin:httpbin"
    volumes:
      - type: bind
        source: ./docker/haproxy
        target: /usr/local/etc/haproxy
      - hap:/var/lib/haproxy

volumes:
  hap:
