version: "3.9"
services:
  httpbin:
    image: mccutchen/go-httpbin:v2.5.0
    ports:
      - 8080:8080
  echoserver:
    image: jmalloc/echo-server
    environment:
      - PORT=8081
    ports:
      - 8081:8081
  coraza:
    image: coraza/coraza-spoa:crs4-test
    volumes:
      - ./docker/e2e/e2e-rules.conf:/etc/coraza-spoa/rules/000-e2e-rules.conf
  haproxy:
    depends_on:
      - coraza
      - httpbin
    image: ${HAPROXY_IMAGE:-haproxy:2.7-alpine}
    ports: [ "4000:80" ]
    links:
      - "coraza:coraza"
      - "httpbin:httpbin"
      - "echoserver:echoserver"
    volumes:
      - type: bind
        source: ./docker/haproxy
        target: /usr/local/etc/haproxy
  tests:
    depends_on:
      - haproxy
      - coraza
    links:
      - "haproxy:haproxy"
      - "httpbin:httpbin"
    build:
      context: docker/e2e
      dockerfile: ./Dockerfile.curl
  wsstat:
    depends_on:
      - haproxy
      - coraza
    links:
      - "haproxy:haproxy"
      - "httpbin:httpbin"
    build:
      context: docker/wsstat
    stdin_open: true
    tty: true

