name: "Build Container Image"
on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
  workflow_dispatch:

env:
  HAPROXY_IMAGES: >
    haproxy:2.2-alpine
    haproxy:2.4-alpine
    haproxy:2.5-alpine
    haproxy:2.6-alpine
    haproxy:2.7-alpine

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

     - name: Run e2e tests against the example
        shell: bash
        run: >
          for image in $HAPROXY_IMAGES; do
              echo "Running e2e with Haproxy image $image"
              HAPROXY_IMAGE=$image docker compose -f docker-compose.e2e.yaml up --abort-on-container-exit test
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
